Load the dataset

Check missing values

Remove duplicates

Handle missing data

Filter records

Create new columns

Group data by department/gender

Sort students

Generate summary statistics

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("student_performance_500.csv")
df

,Student_ID,Name,Gender,Age,Department,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Result
0,STU001,Anu Nair,Female,20,CSE,81.1,78.7,82.0,3.5,0,75.2,Pass
1,STU002,Arun Pillai,Male,22,MCA,96.4,87.2,96.2,5.6,1,78.3,Pass
2,STU003,Meera Das,Male,21,EEE,75.2,87.2,85.2,7.5,1,70.0,Pass
3,STU004,Rahul Sharma,Male,21,ECE,100.0,84.6,88.7,5.2,0,83.5,Pass
4,STU005,Diya Kumar,Male,20,CSE,81.6,68.0,75.3,2.3,0,65.0,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
495,STU496,Devika Joseph,Male,20,EEE,88.7,85.6,74.8,4.9,0,68.9,Pass
496,STU497,Gokul George,Female,21,CSE,80.6,78.4,72.4,4.4,0,67.5,Pass
497,STU498,Kavya Menon,Female,19,CSE,69.8,83.4,73.6,5.0,0,65.1,Pass
498,STU499,Kiran Thomas,Male,23,MCA,79.9,85.4,79.0,5.4,0,75.7,Pass
499,STU500,Maya Varma,Male,23,EEE,73.5,71.3,74.2,5.7,0,67.4,Pass

In [3]:
df.isnull().values.any()

np.False_

In [4]:
df=df.drop_duplicates()

In [5]:
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].mean())
df["Final_Mark"] = df["Final_Mark"].fillna(df["Final_Mark"].mean())

In [6]:
df

,Student_ID,Name,Gender,Age,Department,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Result
0,STU001,Anu Nair,Female,20,CSE,81.1,78.7,82.0,3.5,0,75.2,Pass
1,STU002,Arun Pillai,Male,22,MCA,96.4,87.2,96.2,5.6,1,78.3,Pass
2,STU003,Meera Das,Male,21,EEE,75.2,87.2,85.2,7.5,1,70.0,Pass
3,STU004,Rahul Sharma,Male,21,ECE,100.0,84.6,88.7,5.2,0,83.5,Pass
4,STU005,Diya Kumar,Male,20,CSE,81.6,68.0,75.3,2.3,0,65.0,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
495,STU496,Devika Joseph,Male,20,EEE,88.7,85.6,74.8,4.9,0,68.9,Pass
496,STU497,Gokul George,Female,21,CSE,80.6,78.4,72.4,4.4,0,67.5,Pass
497,STU498,Kavya Menon,Female,19,CSE,69.8,83.4,73.6,5.0,0,65.1,Pass
498,STU499,Kiran Thomas,Male,23,MCA,79.9,85.4,79.0,5.4,0,75.7,Pass
499,STU500,Maya Varma,Male,23,EEE,73.5,71.3,74.2,5.7,0,67.4,Pass

In [7]:
df.isnull().sum()

Student_ID          0
Name                0
Gender              0
Age                 0
Department          0
Attendance          0
Assignment_Score    0
Internal_Mark       0
Study_Hours         0
Backlogs            0
Final_Mark          0
Result              0
dtype: int64

In [8]:
low_attendance = df[df["Attendance"] < 75]
low_attendance

,Student_ID,Name,Gender,Age,Department,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Result
5,STU006,Akhil Joseph,Male,20,CE,67.7,87.2,77.5,5.3,0,80.2,Pass
11,STU012,Anjali Pillai,Male,23,ECE,63.1,75.5,85.4,5.7,1,64.7,Pass
13,STU014,Athira Sharma,Male,20,ME,57.8,83.2,87.8,5.3,2,58.1,Pass
14,STU015,Adithya Kumar,Male,20,CSE,66.2,62.0,57.2,2.9,1,41.9,Fail
18,STU019,Kiran Thomas,Female,20,ECE,72.3,83.5,100.0,7.6,2,82.9,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
463,STU464,Athira Sharma,Male,21,CE,71.0,73.3,76.0,4.0,1,66.7,Pass
479,STU480,Abhinav Varma,Female,21,ECE,69.0,78.4,71.7,3.9,1,61.4,Pass
491,STU492,Anjali Pillai,Male,21,CE,64.4,96.0,99.8,7.0,0,79.8,Pass
497,STU498,Kavya Menon,Female,19,CSE,69.8,83.4,73.6,5.0,0,65.1,Pass
499,STU500,Maya Varma,Male,23,EEE,73.5,71.3,74.2,5.7,0,67.4,Pass

In [9]:
high_scorers = df[df["Final_Mark"] > 80]
high_scorers

,Student_ID,Name,Gender,Age,Department,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Result
3,STU004,Rahul Sharma,Male,21,ECE,100.0,84.6,88.7,5.2,0,83.5,Pass
5,STU006,Akhil Joseph,Male,20,CE,67.7,87.2,77.5,5.3,0,80.2,Pass
6,STU007,Asha George,Female,19,EEE,83.3,92.4,98.7,6.7,0,88.6,Pass
18,STU019,Kiran Thomas,Female,20,ECE,72.3,83.5,100.0,7.6,2,82.9,Pass
25,STU026,Hari Joseph,Female,21,CSE,82.3,91.2,74.9,6.8,1,87.2,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
482,STU483,Meera Das,Female,20,CSE,76.7,82.3,82.1,5.2,0,81.2,Pass
484,STU485,Diya Kumar,Male,21,ME,94.4,83.3,91.1,6.5,1,81.5,Pass
487,STU488,Vishnu Menon,Male,20,ECE,99.0,85.3,100.0,6.8,0,87.0,Pass
493,STU494,Athira Sharma,Female,20,CE,85.8,100.0,100.0,10.0,0,100.0,Pass
494,STU495,Adithya Kumar,Female,20,CE,94.9,93.3,100.0,6.4,0,81.9,Pass

In [10]:
passed = df[df["Result"] == "Pass"]
passed

,Student_ID,Name,Gender,Age,Department,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Result
0,STU001,Anu Nair,Female,20,CSE,81.1,78.7,82.0,3.5,0,75.2,Pass
1,STU002,Arun Pillai,Male,22,MCA,96.4,87.2,96.2,5.6,1,78.3,Pass
2,STU003,Meera Das,Male,21,EEE,75.2,87.2,85.2,7.5,1,70.0,Pass
3,STU004,Rahul Sharma,Male,21,ECE,100.0,84.6,88.7,5.2,0,83.5,Pass
4,STU005,Diya Kumar,Male,20,CSE,81.6,68.0,75.3,2.3,0,65.0,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
495,STU496,Devika Joseph,Male,20,EEE,88.7,85.6,74.8,4.9,0,68.9,Pass
496,STU497,Gokul George,Female,21,CSE,80.6,78.4,72.4,4.4,0,67.5,Pass
497,STU498,Kavya Menon,Female,19,CSE,69.8,83.4,73.6,5.0,0,65.1,Pass
498,STU499,Kiran Thomas,Male,23,MCA,79.9,85.4,79.0,5.4,0,75.7,Pass
499,STU500,Maya Varma,Male,23,EEE,73.5,71.3,74.2,5.7,0,67.4,Pass

In [11]:
df["Total_Score"] = (
    df["Assignment_Score"] +
    df["Internal_Mark"] +
    df["Final_Mark"]
)
df

,Student_ID,Name,Gender,Age,Department,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Result,Total_Score
0,STU001,Anu Nair,Female,20,CSE,81.1,78.7,82.0,3.5,0,75.2,Pass,235.9
1,STU002,Arun Pillai,Male,22,MCA,96.4,87.2,96.2,5.6,1,78.3,Pass,261.7
2,STU003,Meera Das,Male,21,EEE,75.2,87.2,85.2,7.5,1,70.0,Pass,242.4
3,STU004,Rahul Sharma,Male,21,ECE,100.0,84.6,88.7,5.2,0,83.5,Pass,256.8
4,STU005,Diya Kumar,Male,20,CSE,81.6,68.0,75.3,2.3,0,65.0,Pass,208.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,STU496,Devika Joseph,Male,20,EEE,88.7,85.6,74.8,4.9,0,68.9,Pass,229.3
496,STU497,Gokul George,Female,21,CSE,80.6,78.4,72.4,4.4,0,67.5,Pass,218.3
497,STU498,Kavya Menon,Female,19,CSE,69.8,83.4,73.6,5.0,0,65.1,Pass,222.1
498,STU499,Kiran Thomas,Male,23,MCA,79.9,85.4,79.0,5.4,0,75.7,Pass,240.1
499,STU500,Maya Varma,Male,23,EEE,73.5,71.3,74.2,5.7,0,67.4,Pass,212.9

In [12]:
dept_average = df.groupby("Department")["Final_Mark"].mean()
dept_average

Department
CE     72.579012
CSE    69.629299
ECE    71.372368
EEE    72.198611
MCA    70.675472
ME     70.024590
Name: Final_Mark, dtype: float64

In [13]:
gender_average = df.groupby("Gender")["Final_Mark"].mean()
gender_average

Gender
Female    71.107595
Male      70.715209
Name: Final_Mark, dtype: float64

In [14]:
df_sorted = df.sort_values("Final_Mark", ascending=False)
df_sorted

,Student_ID,Name,Gender,Age,Department,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Result,Total_Score
447,STU448,Sreeram Menon,Female,21,MCA,87.6,100.0,100.0,8.5,0,100.0,Pass,300.0
493,STU494,Athira Sharma,Female,20,CE,85.8,100.0,100.0,10.0,0,100.0,Pass,300.0
32,STU033,Meera Das,Male,19,CSE,100.0,97.6,99.7,8.2,1,98.6,Pass,295.9
85,STU086,Hari Joseph,Male,20,ECE,95.8,92.0,100.0,6.7,0,96.8,Pass,288.8
151,STU152,Arun Pillai,Male,20,CSE,85.6,97.3,100.0,10.0,2,95.4,Pass,292.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,STU300,Abhinav Varma,Female,19,CSE,72.8,56.0,59.0,1.6,0,45.5,Fail,160.5
321,STU322,Sanjay Pillai,Male,21,CSE,68.7,68.5,61.3,1.9,1,45.0,Fail,174.8
198,STU199,Kiran Thomas,Male,22,CE,68.1,65.0,64.7,1.0,0,44.9,Fail,174.6
442,STU443,Sneha Das,Female,20,ECE,67.8,53.4,59.7,1.7,0,43.1,Fail,156.2
14,STU015,Adithya Kumar,Male,20,CSE,66.2,62.0,57.2,2.9,1,41.9,Fail,161.1

In [15]:
df.describe()

,Age,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Total_Score
count,500.000000,500.0000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,20.588000,82.6102,78.879000,80.437800,4.597200,0.454000,70.901200,230.218000
std,1.062315,9.7273,10.021763,11.148901,1.757558,0.681772,10.475566,27.364245
min,19.000000,55.0000,48.900000,49.900000,1.000000,0.000000,41.900000,156.200000
25%,20.000000,75.7750,72.300000,73.100000,3.400000,0.000000,64.050000,212.200000
50%,21.000000,82.7000,78.650000,80.250000,4.500000,0.000000,70.850000,229.400000
75%,21.000000,89.3000,85.400000,88.625000,5.800000,1.000000,77.925000,249.000000
max,23.000000,100.0000,100.000000,100.000000,10.000000,4.000000,100.000000,300.000000

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        500 non-null    str
 1   Name              500 non-null    str
 2   Gender            500 non-null    str
 3   Age               500 non-null    int64
 4   Department        500 non-null    str
 5   Attendance        500 non-null    float64
 6   Assignment_Score  500 non-null    float64
 7   Internal_Mark     500 non-null    float64
 8   Study_Hours       500 non-null    float64
 9   Backlogs          500 non-null    int64
 10  Final_Mark        500 non-null    float64
 11  Result            500 non-null    str
 12  Total_Score       500 non-null    float64
dtypes: float64(6), int64(2), str(5)
memory usage: 50.9 KB